### ISSUE TITLE
각종 데이터를 그래프와 상세보기로 분리

### ISSUE THREAD

**Issue by izuzero** [xpressengine/xe-module-profiler#20]
각 기능(탭)마다 데이터를 그래프 보기와 상세 보기(테이블로 데이터 리스트를 보여줌)로 나누는 작업.

**Comment by qw5414** [comment]
첫 화면은 간단한 전체적인 프로파일링 원 그래프를 2개 나타내는 그 작업으로 가고,
disp 을 각각 생성하여, 슬로우 로그를 확인하는 하위 목록을 3가지로 분류, 위젯, 모듈.트리거, 애드온 각분류를 나눔.
기존의 슬로우 로그를 담당하던 곳은 첫 기능이엿던 모듈을 기반으로 쿼리 가져오도록 함.
